/*

 GUSTAV-SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define GustavSpritesBank 0

/* Gameboy Color palette 0 */
#define GustavSpritesCGBPal0c0 19507
#define GustavSpritesCGBPal0c1 30653
#define GustavSpritesCGBPal0c2 9818
#define GustavSpritesCGBPal0c3 6578

/* Gameboy Color palette 1 */
#define GustavSpritesCGBPal1c0 19507
#define GustavSpritesCGBPal1c1 30653
#define GustavSpritesCGBPal1c2 0
#define GustavSpritesCGBPal1c3 9818

/* CGBpalette entries. */
extern const unsigned char GustavSpritesCGB[];
/* Start of tile array. */
extern const unsigned char GustavSprites[];

/* End of GUSTAV-SPRITES.H */
