/*

 PLAYER-SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PlayerSpritesBank 0

/* Gameboy Color palette 1 */
#define PlayerSpritesCGBPal1c0 19507
#define PlayerSpritesCGBPal1c1 15158
#define PlayerSpritesCGBPal1c2 10799
#define PlayerSpritesCGBPal1c3 4295

/* Gameboy Color palette 2 */
#define PlayerSpritesCGBPal2c0 19507
#define PlayerSpritesCGBPal2c1 2131
#define PlayerSpritesCGBPal2c2 10799
#define PlayerSpritesCGBPal2c3 4295

/* CGBpalette entries. */
extern const unsigned char PlayerSpritesCGB[];
/* Start of tile array. */
extern const unsigned char PlayerSprites[];

/* End of PLAYER-SPRITES.H */
