/*

 PLAYER-IDLE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 6

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PlayerIdleBank 0

/* Super Gameboy palette 0 */
#define PlayerIdleSGBPal0c0 6076
#define PlayerIdleSGBPal0c1 8935
#define PlayerIdleSGBPal0c2 6596
#define PlayerIdleSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerIdleSGBPal1c0 6076
#define PlayerIdleSGBPal1c1 8935
#define PlayerIdleSGBPal1c2 6596
#define PlayerIdleSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerIdleSGBPal2c0 6076
#define PlayerIdleSGBPal2c1 8935
#define PlayerIdleSGBPal2c2 6596
#define PlayerIdleSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerIdleSGBPal3c0 6076
#define PlayerIdleSGBPal3c1 8935
#define PlayerIdleSGBPal3c2 6596
#define PlayerIdleSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerIdleCGBPal0c0 19507
#define PlayerIdleCGBPal0c1 19507
#define PlayerIdleCGBPal0c2 19507
#define PlayerIdleCGBPal0c3 19507

/* Gameboy Color palette 1 */
#define PlayerIdleCGBPal1c0 19507
#define PlayerIdleCGBPal1c1 15158
#define PlayerIdleCGBPal1c2 10799
#define PlayerIdleCGBPal1c3 4295

/* Gameboy Color palette 2 */
#define PlayerIdleCGBPal2c0 19507
#define PlayerIdleCGBPal2c1 2131
#define PlayerIdleCGBPal2c2 10799
#define PlayerIdleCGBPal2c3 4295

/* Gameboy Color palette 3 */
#define PlayerIdleCGBPal3c0 6076
#define PlayerIdleCGBPal3c1 8935
#define PlayerIdleCGBPal3c2 6596
#define PlayerIdleCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerIdleCGBPal4c0 6076
#define PlayerIdleCGBPal4c1 8935
#define PlayerIdleCGBPal4c2 6596
#define PlayerIdleCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerIdleCGBPal5c0 6076
#define PlayerIdleCGBPal5c1 8935
#define PlayerIdleCGBPal5c2 6596
#define PlayerIdleCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerIdleCGBPal6c0 6076
#define PlayerIdleCGBPal6c1 8935
#define PlayerIdleCGBPal6c2 6596
#define PlayerIdleCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerIdleCGBPal7c0 6076
#define PlayerIdleCGBPal7c1 8935
#define PlayerIdleCGBPal7c2 6596
#define PlayerIdleCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char PlayerIdleCGB[];
/* Start of tile array. */
extern unsigned char PlayerIdle[];

/* End of PLAYER-IDLE.H */
