/*

 PLAYER-SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 16

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PlayerSpritesBank 0

/* Super Gameboy palette 0 */
#define PlayerSpritesSGBPal0c0 6076
#define PlayerSpritesSGBPal0c1 8935
#define PlayerSpritesSGBPal0c2 6596
#define PlayerSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerSpritesSGBPal1c0 6076
#define PlayerSpritesSGBPal1c1 8935
#define PlayerSpritesSGBPal1c2 6596
#define PlayerSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerSpritesSGBPal2c0 6076
#define PlayerSpritesSGBPal2c1 8935
#define PlayerSpritesSGBPal2c2 6596
#define PlayerSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerSpritesSGBPal3c0 6076
#define PlayerSpritesSGBPal3c1 8935
#define PlayerSpritesSGBPal3c2 6596
#define PlayerSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerSpritesCGBPal0c0 19507
#define PlayerSpritesCGBPal0c1 19507
#define PlayerSpritesCGBPal0c2 19507
#define PlayerSpritesCGBPal0c3 19507

/* Gameboy Color palette 1 */
#define PlayerSpritesCGBPal1c0 19507
#define PlayerSpritesCGBPal1c1 15158
#define PlayerSpritesCGBPal1c2 10799
#define PlayerSpritesCGBPal1c3 4295

/* Gameboy Color palette 2 */
#define PlayerSpritesCGBPal2c0 19507
#define PlayerSpritesCGBPal2c1 2131
#define PlayerSpritesCGBPal2c2 10799
#define PlayerSpritesCGBPal2c3 4295

/* Gameboy Color palette 3 */
#define PlayerSpritesCGBPal3c0 6076
#define PlayerSpritesCGBPal3c1 8935
#define PlayerSpritesCGBPal3c2 6596
#define PlayerSpritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerSpritesCGBPal4c0 6076
#define PlayerSpritesCGBPal4c1 8935
#define PlayerSpritesCGBPal4c2 6596
#define PlayerSpritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerSpritesCGBPal5c0 6076
#define PlayerSpritesCGBPal5c1 8935
#define PlayerSpritesCGBPal5c2 6596
#define PlayerSpritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerSpritesCGBPal6c0 6076
#define PlayerSpritesCGBPal6c1 8935
#define PlayerSpritesCGBPal6c2 6596
#define PlayerSpritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerSpritesCGBPal7c0 6076
#define PlayerSpritesCGBPal7c1 8935
#define PlayerSpritesCGBPal7c2 6596
#define PlayerSpritesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char PlayerSpritesCGB[];
/* Start of tile array. */
extern unsigned char PlayerSprites[];

/* End of PLAYER-SPRITES.H */
